[package]
name = "georust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
rand = {version = "0.7.3", features = ["wasm-bindgen"] }
gloo = "0.6.1"